name: Create Pull Request

on:
  workflow_dispatch:  # Enable manual triggering
  push:
    branches:
      - 'AB*'

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Check for existing pull request
        id: check_pr
        run: |
          response=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.ref }}&state=open")
          if [ "$(echo $response | jq length)" -gt 0 ]; then
            echo "PR exists for branch ${{ github.ref }}"
            echo "::set-output name=pr_exists::true"
          else
            echo "PR does not exist for branch ${{ github.ref }}"
            echo "::set-output name=pr_exists::false"
          fi

      - name: Print pr_exists
        run: |
          echo "pr_exists: ${{ steps.check_pr.outputs.pr_exists }}"

      - name: Create Pull Request
        if: steps.check_pr.outputs.pr_exists != 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: "${{ github.event.head_commit.message }}"
          body: |
            This pull request adds the following changes:

            ${{ github.event.head_commit.message }}

          branch: ${{ github.ref }}
          base: master
          assignees: ${{ github.actor }}  # Set the pusher as the assignee
