name: Create Pull Request

on:
  workflow_dispatch: # Enable manual triggering
  push:
    branches:
      - 'AB*'

jobs:
  create_pull_request:
    name: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ github.event.commits[0].message }}"
          body: |
            This pull request adds the following changes:

            ${{ github.event.commits[0].message }}

          branch: AB#test2
          base: master
          assignees: ${{github.actor}}
